export const featuredListings = [
    {
      title: "Janet Poole House",
      imageUrl: "/list-1.jpg",
      price: "£399",
      walking: "4 mins",
      car: "20 mins",
        train:"10 mins",
      cheapest: "Cheapest in the past 5 month",
      voucher: "£100 Uber voucher",
    },
    {
      title: "Stuhomes Student Living Heights",
      imageUrl: "/list-2.jpg",
      price: "£345",
      walking: "34 mins",
      car: "20 mins",
        train:"10 mins",
      cheapest: "Cheapest in the past month",
    },
    {
      title: "Flat 39, Forsyth House",
      imageUrl: "/list-3.jpg",
      price: "£202",
      walking: "40 mins",
      car: "20 mins",
      train:"10 mins",
      cheapest: "Cheapest in the two year",
    },
    {
        title: "Flat 49, Forsyth House",
        imageUrl: "/list-4.jpg",
        price: "£200",
        walking: "20 mins",
        car: "20 mins",
        train:"10 mins",
        cheapest: "Cheapest in the past one year",
      },
      
  ];

export const detailedListings = [
    {
      title: "Stuhomes Student Living Heights",
      imageUrl: "/list-1.jpg",
      price: "£345",
      walking: "15 mins",
      car: "10 mins",
      train:"5 mins",

      facilities: [
        "Laundry Facilities in Room",
        "Refrigerator",
        "WiFi",
        "Bike Storage",
        "Reception",
      ],
      description:
        "Student Living Heights is ideally located near various universities, making it a great choice for those who want to cut down on commute time.",
      cheapest: "Cheapest in the past month",
    },
    {
      title: "Rathbone Apartments",
      imageUrl: "/list-2.jpg",
      price: "£315",
      walking: "15 mins",
      car: "10 mins",
      train:"5 mins",
      facilities: [
        "Kitchen",
        "Furnished",
        "On-site Laundry (Free)",
        "WiFi",
        "On-site Manager",
      ],
      description:
        "Rathbone Apartments is just a stone's throw from Oxford Street's flagship stores and the cultural center that is London's theatre district.",
      cheapest: "Cheapest in the past 5 months",
    },
    {
        title: "Flat 39, Forsyth House",
      imageUrl: "/list-3.jpg",
        price: "£315",
        walking: "20 mins",
        car: "20 mins",
        train:"10 mins",
        facilities: [
          "Kitchen",
          "Furnished",
          "On-site Laundry (Free)",
          "WiFi",
          "On-site Manager",
        ],
        description:
          "Rathbone Apartments is just a stone's throw from Oxford Street's flagship stores and the cultural center that is London's theatre district.",
        cheapest: "Cheapest in the past 5 months",
      },
      {
        title: "Flat 49, Forsyth House",
        imageUrl: "/list-4.jpg",
        price: "£315",
        walking: "40 mins",
      car: "20 mins",
      train:"10 mins",
        facilities: [
          "Kitchen",
          "Furnished",
          "On-site Laundry (Free)",
          "WiFi",
          "On-site Manager",
        ],
        description:
          "Rathbone Apartments is just a stone's throw from Oxford Street's flagship stores and the cultural center that is London's theatre district.",
        cheapest: "Cheapest in the past 5 months",
      },
      {
        title: "Flat 60, Forsyth House",
        imageUrl: "/list-5.jpg",
        price: "£315",
        walking: "34 mins",
      car: "20 mins",
        train:"10 mins",
        facilities: [
          "Kitchen",
          "Furnished",
          "On-site Laundry (Free)",
          "WiFi",
          "On-site Manager",
        ],
        description:
          "Rathbone Apartments is just a stone's throw from Oxford Street's flagship stores and the cultural center that is London's theatre district.",
        cheapest: "Cheapest in the past 5 months",
      },
      {
        title: "Flat 90, Forsyth House",
        imageUrl: "/list-6.jpg",
        price: "£315",
        walking: "4 mins",
        car: "20 mins",
          train:"10 mins",
        facilities: [
          "Kitchen",
          "Furnished",
          "On-site Laundry (Free)",
          "WiFi",
          "On-site Manager",
        ],
        description:
          "Rathbone Apartments is just a stone's throw from Oxford Street's flagship stores and the cultural center that is London's theatre district.",
        cheapest: "Cheapest in the past 5 months",
      },
  ];